<?php

function sandbox_menu() {
  $items['test-page'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sandbox_test_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function sandbox_test_form($form, &$form_state) {
  $form = array(
    '#prefix' => '<div id="test-wrapper">',
    '#suffix' => '</div>'
  );

  $form['fields'] = array(
    '#prefix' => '<div id="test-fields">',
    '#suffix' => '</div>'
  );

  if (empty($form_state['executed'])) {
    $form_state['fields'] = array();
    $form_state['last_field'] = 0;
  }
  else {
    $form_state['fields'] = $form_state['fields'];
    $form_state['last_field'] = $form_state['last_field'];

    foreach ($form_state['fields'] AS $value) {
      $form['fields']['field_' . $value] = array(
        '#type' => 'textfield',
        '#title' => 'Label ' . $value
      );
    }
  }

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
    '#name' => 'test_submit',
    '#ajax' => array(
      'callback' => 'sandbox_test_form_ajax',
      'progress' => array(
        'message' => '',
        'type' => 'throbber'
      ),
    ),
    '#submit' => array('sandbox_test_form_submit'),
  );
  return $form;
}

function sandbox_test_form_submit($form, &$form_state) {
  $new_field = $form_state['last_field'] + 1;
  $form_state['last_field'] = $new_field;
  $form_state['fields'][$new_field] = $new_field;
  $form_state['rebuild'] = TRUE;
//  drupal_set_message('<pre>' . print_r($form_state['values'], TRUE) . '</pre>');
}

function sandbox_test_form_ajax($form, &$form_state) {
  $commands = array();

  $commands[] = ajax_command_invoke('#test-fields', 'append', array(render($form['fields']['field_' . $form_state['last_field']])));

  $element = array('#type' => 'ajax', '#commands' => $commands);
  return $element;
}
